### ISSUE TITLE
Improve areaMutation GQL to support grade context

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#165]
### Use case
As a contributor I want to set the default grade context for an area.

### Todo
- [ ] Add grade context to GQL [typedef](https://github.com/OpenBeta/openbeta-graphql/blob/staging/src/graphql/area/AreaEditTypeDef.ts#L44)
- [ ] Update the corresponding type
- [ ] Record grade context object in db.  https://github.com/OpenBeta/openbeta-graphql/blob/cad0ccbfb125b2b7fa1c7cd3b19a9187a74385dc/src/model/MutableAreaDataSource.ts#L294-L297
