### ISSUE TITLE
Prototype change history tracking

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#88]
How do we track edit history?

For this prototype
- [x] Use Mongo `watch` to save changes to Media collection to media_history collection
- [x] Implement 'soft' delete
- [ ] Implement undo-last-change operation

https://www.mongodb.com/docs/manual/changeStreams/
